name: Build

on:
  push:
    branches:
      - stable
      - main
    paths:
      - '**.java'
  pull_request:
    branches:
      - main
    paths:
      - '**.java'
  workflow_dispatch:
    inputs:
      upload_artifact:
        description: 'Upload artifact to this run? [yes | no]'
        required: false
        default: 'yes'

jobs:
  build:
    name: Build
    if: ${{ !contains(github.head_ref, 'translations/') }}
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_buildNumber: ${{ github.run_number }}
      ORG_GRADLE_PROJECT_runAttempt: ${{ github.run_attempt }}
      ORG_GRADLE_PROJECT_runningOnCi: true
      UPLOAD_ARTIFACT_ENABLED: true
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '18'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Read project version
        id: read_project_version
        if: ${{ env.UPLOAD_ARTIFACT_ENABLED || contains(github.event.inputs.upload_artifact, 'yes') }}
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: gradle.properties
          property: version

      - name: Upload build artifact
        if: ${{ env.UPLOAD_ARTIFACT_ENABLED || contains(github.event.inputs.upload_artifact, 'yes') }}
        env:
          project_version: ${{ steps.read_project_version.outputs.value }}
        uses: actions/upload-artifact@v4
        with:
          name: SkyblockAddons v${{ env.project_version }}+${{ env.ORG_GRADLE_PROJECT_buildNumber }}
          path: build/libs/*
